In [20]:
import pandas as pd

In [33]:
data = pd.read_csv("olist_public_dataset_v2.csv")
data = data.set_index('order_id')
data.head()

,order_status,order_products_value,order_freight_value,order_items_qty,order_sellers_qty,order_purchase_timestamp,order_aproved_at,order_estimated_delivery_date,order_delivered_customer_date,customer_id,...,product_name_lenght,product_description_lenght,product_photos_qty,product_id,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
order_id,,,,,,,,,,,,,,,,,,,,,
b95df3cef5297e79ef709ba256518f6f,delivered,349.90,13.84,1,1,2017-01-31 17:19:01.000000,2017-02-01 02:41:21.549551,2017-03-15 00:00:00.000000,2017-02-06 11:04:24.154259,297dcf281305aabfee256d313076af2b,...,51,625,1,6cdd53843498f92890544667809f1595,b95df3cef5297e79ef709ba256518f6f,5,NaN,NaN,2017-02-07 00:00:00.000000,2017-02-09 02:37:37+00:00
59af46052a799e80e2f0c665c587731d,delivered,15.00,15.10,1,1,2017-09-09 19:52:54.000000,2017-09-10 20:03:31.535281,2017-10-02 00:00:00.000000,2017-09-13 20:17:41.296915,b7563d94162ed0aa3f8d9cada4bcc536,...,44,1428,2,ae5cad88462eb7b7b61401e31c45618e,59af46052a799e80e2f0c665c587731d,5,NaN,entrega em 2 dias produto c boa qualidade otim...,2017-09-14 00:00:00.000000,2017-09-15 03:43:47+00:00
a3e6136894621db402a772c6bc72a12a,delivered,238.90,18.00,1,1,2017-01-30 17:00:09.000000,2017-01-30 17:31:25.438253,2017-03-07 00:00:00.000000,2017-02-06 15:43:04.758566,f102cb15ec41ca30fa2902da06495f6b,...,55,637,1,0c9ff9d8ed9b9bdd825487b3a66e05f5,a3e6136894621db402a772c6bc72a12a,5,NaN,produto veio antes do prazo informado muito ob...,2017-02-07 00:00:00.000000,2017-02-10 14:18:53+00:00
b675ea5a618922f6e679e30531b8957b,delivered,29.99,18.23,1,1,2018-03-11 18:18:36.000000,2018-03-11 18:30:37.931962,2018-04-03 00:00:00.000000,2018-04-03 20:36:43.778451,e33c250311160298e5b457ca52720a35,...,55,617,1,ad0a798e7941f3a5a2fb8139cb62ad78,b675ea5a618922f6e679e30531b8957b,4,NaN,NaN,2018-04-04 00:00:00.000000,2018-04-05 02:52:31+00:00
195a8be6794c487fe6cfbb97b7c61902,delivered,295.99,47.65,1,1,2017-04-20 08:01:08.000000,2017-04-25 08:05:40.405383,2017-05-24 00:00:00.000000,2017-05-04 18:47:45.721758,8a8f7c9a4450f17ba3ee25a5ba821bc7,...,49,558,2,eaf2046d4c87809247a30050ea13df03,195a8be6794c487fe6cfbb97b7c61902,5,NaN,NaN,2017-05-05 00:00:00.000000,2017-05-08 15:20:18+00:00

In [34]:
dados_treinamento = data[:int((len(data)/10))*6]
dados_teste = data[int((len(data)/10))*6:]
data = dados_treinamento

dados_treinamento.to_csv('dados_treinamento.csv')
dados_teste.to_csv('dados_teste.csv')

In [35]:
%matplotlib notebook


import pandas as pd
import numpy as np
from scipy.stats import norm, probplot
import statsmodels.api as sm
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [41]:
data.columns

Index(['order_status', 'order_products_value', 'order_freight_value',
       'order_items_qty', 'order_sellers_qty', 'order_purchase_timestamp',
       'order_aproved_at', 'order_estimated_delivery_date',
       'order_delivered_customer_date', 'customer_id', 'customer_city',
       'customer_state', 'customer_zip_code_prefix', 'product_category_name',
       'product_name_lenght', 'product_description_lenght',
       'product_photos_qty', 'product_id', 'review_id', 'review_score',
       'review_comment_title', 'review_comment_message',
       'review_creation_date', 'review_answer_timestamp'],
      dtype='object')

In [44]:
df = data[['order_products_value', 'order_freight_value', 'product_description_lenght', 'product_photos_qty', 'review_score', 'review_comment_message']]

In [46]:
df.head()

,order_products_value,order_freight_value,product_description_lenght,product_photos_qty,review_score,review_comment_message
order_id,,,,,,
b95df3cef5297e79ef709ba256518f6f,349.90,13.84,625,1,5,NaN
59af46052a799e80e2f0c665c587731d,15.00,15.10,1428,2,5,entrega em 2 dias produto c boa qualidade otim...
a3e6136894621db402a772c6bc72a12a,238.90,18.00,637,1,5,produto veio antes do prazo informado muito ob...
b675ea5a618922f6e679e30531b8957b,29.99,18.23,617,1,4,NaN
195a8be6794c487fe6cfbb97b7c61902,295.99,47.65,558,2,5,NaN

In [52]:
### FunÃ§Ã£o utilitÃ¡ria para fazer a regressÃ£o com constante adicionada
def regress(X,Y):
    X_cp = sm.add_constant(X)
    model = sm.OLS(Y,X_cp)
    results = model.fit()
    return results

In [62]:
y = df['review_score']
x = df[['order_products_value', 'order_freight_value', 'product_description_lenght', 'product_photos_qty']]
x.head()

,order_products_value,order_freight_value,product_description_lenght,product_photos_qty
order_id,,,,
b95df3cef5297e79ef709ba256518f6f,349.90,13.84,625,1
59af46052a799e80e2f0c665c587731d,15.00,15.10,1428,2
a3e6136894621db402a772c6bc72a12a,238.90,18.00,637,1
b675ea5a618922f6e679e30531b8957b,29.99,18.23,617,1
195a8be6794c487fe6cfbb97b7c61902,295.99,47.65,558,2

In [58]:
results = regress(x,y)
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:           review_score   R-squared:                       0.007
Model:                            OLS   Adj. R-squared:                  0.007
Method:                 Least Squares   F-statistic:                     102.8
Date:                Thu, 01 Nov 2018   Prob (F-statistic):           2.03e-87
Time:                        14:59:59   Log-Likelihood:            -1.0357e+05
No. Observations:               60000   AIC:                         2.071e+05
Df Residuals:                   59995   BIC:                         2.072e+05
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
const                          4.1071      0.012    339.063      0.000       4.083       4.131
order_products_value           0.0001   3.38e-05      3.394      0.001    4.84e-05       0.000
order_freight_value           -0.0056      0.000    -18.849      0.000      -0.006      -0.005
product_description_lenght  3.553e-05   8.61e-06      4.126      0.000    1.87e-05    5.24e-05
product_photos_qty             0.0114      0.003      3.575      0.000       0.005       0.018
==============================================================================
Omnibus:                    10443.513   Durbin-Watson:                   1.994
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            16942.443
Skew:                          -1.291   Prob(JB):                         0.00
Kurtosis:                       3.337   Cond. No.                     2.27e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.27e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [64]:
c = results.params["const"]
b0 = results.params["order_products_value"]
b1 = results.params["order_freight_value"]
b2 = results.params["product_description_lenght"]
b3 = results.params["product_photos_qty"]

In [84]:
def f(price, frete, description, photos):
    return int((c + b0*price**2 + b1*frete**2 + b2*description**2 + b3*photos**2)**0.5)

In [85]:
f(349.90, 13.84, 625, 1)

5

In [63]:
# delta_delivery = data["order_delivered_customer_date"] - data["order_estimated_delivery_date"]
# delta_delivery